-- 백 발생한 에러 적재
CREATE SEQUENCE SEQ_TKW_BACK_LOG START 1;
CREATE TABLE TKW_BACK_LOG
(
    BACK_LOG_ID INTEGER DEFAULT NEXTVAL('SEQ_TKW_BACK_LOG') NOT NULL PRIMARY KEY,
    BACK_LOG_MESSAGE TEXT,
    BACK_LOG_OCCUR_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN TKW_BACK_LOG.BACK_LOG_SEQUENCE IS '로그 sequence 번호';
COMMENT ON COLUMN TKW_BACK_LOG.BACK_LOG_MESSAGE IS '에러 로그 메시지';
COMMENT ON COLUMN TKW_BACK_LOG.BACK_LOG_OCCUR_TIME IS '에러 로그 발생 시간';

-- 프론트 발생한 에러 적재
CREATE SEQUENCE SEQ_TKW_FRONT_LOG START 1;
CREATE TABLE TKW_FRONT_LOG
(
    FRONT_LOG_ID INTEGER DEFAULT NEXTVAL('SEQ_TKW_FRONT_LOG') NOT NULL PRIMARY KEY,
    FRONT_LOG_MESSAGE TEXT,
    FRONT_LOG_OCCUR_TIME timestamp with time zone default now()
)
COMMENT ON COLUMN TKW_FRONT_LOG.FRONT_LOG_SEQUENCE IS '로그 sequence 번호';
COMMENT ON COLUMN TKW_FRONT_LOG.FRONT_LOG_MESSAGE IS '에러 로그 메시지';
COMMENT ON COLUMN TKW_FRONT_LOG.FRONT_LOG_OCCUR_TIME IS '에러 로그 발생 시간';

-- tarkov tweeter 업데이트 소식
CREATE TABLE TKW_X
(
    X_ID VARCHAR(30) NOT NULL PRIMARY KEY,
    X_UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN TKW_X.X_ID IS 'X 게시판 ID';
COMMENT ON COLUMN TKW_X.X_UPDATE_TIME IS 'DB 업데이트 시간';

-- map dae 파일 링크 주소, item 위치 정보 보내기
CREATE TABLE TKW_THREE_MAP
(
    THREE_MAP_ID VARCHAR(30) NOT NULL PRIMARY KEY,
    THREE_MAP_NAME VARCHAR(30) NOT NULL,
    THREE_MAP_PATH TEXT NOT NULL,
    THREE_MAP_ITEM_PATH JSONB NOT NULL,
    THREE_MAP_UPLOAD_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN TKW_THREE_MAP.THREE_MAP_ID IS '3D 지도 ID';
COMMENT ON COLUMN TKW_THREE_MAP.THREE_MAP_NAME IS '3D 지도 이름';
COMMENT ON COLUMN TKW_THREE_MAP.THREE_MAP_PATH IS '3D 지도 nas 저장 경로';
COMMENT ON COLUMN TKW_THREE_MAP.THREE_MAP_ITEM_PATH IS '3D 지도 아이템 좌표 경로 (ThreeJS xyz)';
COMMENT ON COLUMN TKW_THREE_MAP.THREE_MAP_UPLOAD_TIME IS '3D 지도 업로드 시간';

-- map 2d
CREATE TABLE TKW_JPG_MAP
(
    JPG_MAP_ID VARCHAR(30) NOT NULL PRIMARY KEY,
    JPG_MAP_NAME VARCHAR(30) NOT NULL,
    JPG_MAP_PATH TEXT NOT NULL,
    JPG_MAP_UPLOAD_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN TKW_JPG_MAP.JPG_MAP_ID IS '2D 지도 ID';
COMMENT ON COLUMN TKW_JPG_MAP.JPG_MAP_NAME IS '2D 지도 이름';
COMMENT ON COLUMN TKW_JPG_MAP.JPG_MAP_PATH IS '2D 지도 nas 저장 경로';
COMMENT ON COLUMN TKW_JPG_MAP.JPG_MAP_UPLOAD_TIME IS '2D 지도 업로드 시간';

-- 퀘스트 정보 및 공략 (ex: 카파런 최단루트)
CREATE SEQUENCE SEQ_TKW_QUEST_INFO START 1;
CREATE TABLE TKW_QUEST_INFO
(
    QUEST_ID INTEGER DEFAULT NEXTVAL('SEQ_TKW_QUEST_INFO') NOT NULL PRIMARY KEY,
);

-- 탄약 정보
CREATE SEQUENCE SEQ_TKW_QUEST_INFO START 1;
CREATE TABLE TKW_QUEST_INFO
(
    QUEST_ID INTEGER DEFAULT NEXTVAL('SEQ_TKW_QUEST_INFO') NOT NULL PRIMARY KEY,
);

-- 보스 정보
CREATE SEQUENCE SEQ_TKW_BOSS_INFO START 1;
CREATE TABLE TKW_BOSS_INFO
(
    BOSS_ID INTEGER DEFAULT NEXTVAL('SEQ_TKW_BOSS_INFO') NOT NULL PRIMARY KEY,
);

-- 레이더,스캐브,보스,컬티스트,로그 드랍템
CREATE SEQUENCE SEQ_TKW_DROP_ITEM START 1;
CREATE TABLE TKW_DROP_ITEM
(
    DROP_ITEM_ID INTEGER DEFAULT NEXTVAL('SEQ_TKW_DROP_ITEM') NOT NULL PRIMARY KEY,
);

-- 아이템 정보 (ex: 총알, 갑바,컨테이너,리그,가방,키,헤드셋,무기,의약품)
CREATE SEQUENCE SEQ_TKW_ITEM_INFO START 1;
CREATE TABLE TKW_ITEM_INFO
(
    ITEM_ID INTEGER DEFAULT NEXTVAL('SEQ_TKW_ITEM_INFO') NOT NULL PRIMARY KEY,
);

-- 하이드아웃 정보 (ex: 단계별 필요 아이템)
CREATE SEQUENCE SEQ_TKW_HIDEOUT_INFO START 1;
CREATE TABLE TKW_HIDEOUT_INFO
(
    HIDEOUT_ID INTEGER DEFAULT NEXTVAL('SEQ_TKW_HIDEOUT_INFO') NOT NULL PRIMARY KEY,
);