CREATE TABLE BOSS_I18N
(
    ID TEXT NOT NULL PRIMARY KEY,
    NAME JSONB,
    IS_BOSS BOOLEAN,
    PARENT_ID TEXT,
    FACTION TEXT,
    IMAGE TEXT,
    HEALTH_TOTAL INTEGER,
    ITEM_INFO JSONB,
    SPAWN_CHANCE JSONB,
    LOCATION_GUIDE JSONB,
    "order" INTEGER,
    UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN BOSS_I18N.ID IS 'Boss ID';
COMMENT ON COLUMN BOSS_I18N.NAME IS 'Boss 이름';
COMMENT ON COLUMN BOSS_I18N.IS_BOSS IS 'Boss 보스 여부';
COMMENT ON COLUMN BOSS_I18N.PARENT_ID IS 'Boss 추종자의 경우 상위 ID';
COMMENT ON COLUMN BOSS_I18N.FACTION IS 'Boss 소속';
COMMENT ON COLUMN BOSS_I18N.LOCATION_SPAWN_CHANCE IS 'Boss 위치 및 스폰 확률';
COMMENT ON COLUMN BOSS_I18N.IMAGE IS 'Boss 이미지 경로';
COMMENT ON COLUMN BOSS_I18N.ITEM_INFO IS 'Boss 아이템 정보';
COMMENT ON COLUMN BOSS_I18N.HEALTH_TOTAL IS 'Boss 체력';
COMMENT ON COLUMN BOSS_I18N.LOCATION_GUIDE IS 'Boss 위치 가이드';
COMMENT ON COLUMN BOSS_I18N.ORDER IS 'Boss 순서';
COMMENT ON COLUMN BOSS_I18N.UPDATE_TIME IS 'Boss 업데이트 시간';

CREATE TABLE EXTRACTION_I18N
(
  ID TEXT NOT NULL PRIMARY KEY,
  NAME JSONB,
  ALWAYS_AVAILABLE BOOLEAN,
  SINGLE_USE BOOLEAN,
  IMAGE TEXT,
  FACTION TEXT,
  MAP TEXT,
  IMAGE_THUMBNAIL TEXT,
  REQUIREMENTS JSONB,
  TIP JSONB,
  UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN EXTRACTION_I18N.ID IS '탈출구 아이디';
COMMENT ON COLUMN EXTRACTION_I18N.NAME IS '탈출구 이름';
COMMENT ON COLUMN EXTRACTION_I18N.IMAGE IS '탈출구 사진';
COMMENT ON COLUMN EXTRACTION_I18N.FACTION IS '탈출구 소속';
COMMENT ON COLUMN EXTRACTION_I18N.ALWAYS_AVAILABLE IS '탈출구 항상 열림 여부';
COMMENT ON COLUMN EXTRACTION_I18N.SINGLE_USE IS '탈출구 한 번 사용 가능 여부';
COMMENT ON COLUMN EXTRACTION_I18N.REQUIREMENTS IS '탈출구 요구사항';
COMMENT ON COLUMN EXTRACTION_I18N.TIP IS '탈출구 팁';
COMMENT ON COLUMN EXTRACTION_I18N.MAP IS '탈출구 지역';
COMMENT ON COLUMN EXTRACTION_I18N.IMAGE_THUMBNAIL IS '탈출구 썸네일';
COMMENT ON COLUMN EXTRACTION_I18N.UPDATE_TIME IS '탈출구 업데이트 시간';

CREATE TABLE TRANSIT_I18N
(
  ID TEXT NOT NULL PRIMARY KEY,
  NAME JSONB,
  ALWAYS_AVAILABLE BOOLEAN,
  SINGLE_USE BOOLEAN,
  IMAGE TEXT,
  FACTION TEXT,
  MAP TEXT,
  IMAGE_THUMBNAIL TEXT,
  REQUIREMENTS JSONB,
  TIP JSONB,
  UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN TRANSIT_I18N.ID IS 'Transit 아이디';
COMMENT ON COLUMN TRANSIT_I18N.NAME IS 'Transit 이름';
COMMENT ON COLUMN TRANSIT_I18N.IMAGE IS 'Transit 사진';
COMMENT ON COLUMN TRANSIT_I18N.FACTION IS 'Transit 소속';
COMMENT ON COLUMN TRANSIT_I18N.ALWAYS_AVAILABLE IS 'Transit 항상 열림 여부';
COMMENT ON COLUMN TRANSIT_I18N.SINGLE_USE IS 'Transit 한 번 사용 가능 여부';
COMMENT ON COLUMN TRANSIT_I18N.REQUIREMENTS IS 'Transit 요구사항';
COMMENT ON COLUMN TRANSIT_I18N.TIP IS 'Transit 노트';
COMMENT ON COLUMN TRANSIT_I18N.MAP IS 'Transit 지역';
COMMENT ON COLUMN TRANSIT_I18N.IMAGE_THUMBNAIL IS 'Transit 썸네일';
COMMENT ON COLUMN TRANSIT_I18N.UPDATE_TIME IS 'Transit 업데이트 시간';

CREATE TABLE FILTER_GROUP_I18N (
    VALUE TEXT NOT NULL PRIMARY KEY,
    NAME JSONB,
    UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN FILTER_GROUP_I18N.VALUE IS 'Filter 값';
COMMENT ON COLUMN FILTER_GROUP_I18N.NAME IS 'Filter 이름';
COMMENT ON COLUMN FILTER_GROUP_I18N.UPDATE_TIME IS 'Filter 업데이트 시간';

CREATE TABLE FILTER_SUB_GROUP_I18N (
    VALUE TEXT NOT NULL PRIMARY KEY,
    NAME JSONB,
    PARENT_VALUE TEXT,
    UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN FILTER_SUB_GROUP_I18N.VALUE IS 'Filter Sub 값';
COMMENT ON COLUMN FILTER_SUB_GROUP_I18N.NAME IS 'Filter Sub 이름';
COMMENT ON COLUMN FILTER_SUB_GROUP_I18N.PARENT_VALUE IS 'Filter Sub 상위 키';
COMMENT ON COLUMN FILTER_SUB_GROUP_I18N.UPDATE_TIME IS 'Filter Sub 업데이트 시간';

CREATE TABLE MAIN_I18N
(
  VALUE TEXT NOT NULL PRIMARY KEY,
  NAME JSONB,
  LINK TEXT,
  "order" INTEGER,
  IMAGE TEXT,
  USE_SLIDE BOOLEAN,
  SLIDE_IMAGE TEXT,
  UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN MAIN_I18N.VALUE IS 'Menu 값';
COMMENT ON COLUMN MAIN_I18N.NAME IS 'Menu 이름';
COMMENT ON COLUMN MAIN_I18N.LINK IS 'Menu 주소';
COMMENT ON COLUMN MAIN_I18N."order" IS 'Menu 순서';
COMMENT ON COLUMN MAIN_I18N.IMAGE IS 'Menu 이미지';
COMMENT ON COLUMN MAIN_I18N.USE_SLIDE IS 'Menu 슬라이드 여부';
COMMENT ON COLUMN MAIN_I18N.SLIDE_IMAGE IS 'Menu slide 이미지';
COMMENT ON COLUMN MAIN_I18N.UPDATE_TIME IS 'Menu 업데이트 시간';

CREATE TABLE MENU_GROUP_I18N
(
  VALUE TEXT NOT NULL PRIMARY KEY,
  NAME JSONB,
  "order" INTEGER,
  UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN MENU_GROUP_I18N.VALUE IS 'Menu 값';
COMMENT ON COLUMN MENU_GROUP_I18N.NAME IS 'Menu 이름';
COMMENT ON COLUMN MENU_GROUP_I18N."order" IS 'Menu 순서';
COMMENT ON COLUMN MENU_GROUP_I18N.UPDATE_TIME IS 'Menu 업데이트 시간';

CREATE TABLE MENU_SUB_GROUP_I18N
(
  VALUE TEXT NOT NULL PRIMARY KEY,
  NAME JSONB,
  PARENT_VALUE TEXT,
  LINK TEXT,
  "order" INTEGER,
  UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN MENU_SUB_GROUP_I18N.VALUE IS 'Menu 값';
COMMENT ON COLUMN MENU_SUB_GROUP_I18N.NAME IS 'Menu 이름';
COMMENT ON COLUMN MENU_SUB_GROUP_I18N.PARENT_VALUE IS 'Menu 상위 값';
COMMENT ON COLUMN MENU_SUB_GROUP_I18N.LINK IS 'Menu 주소';
COMMENT ON COLUMN MENU_SUB_GROUP_I18N."order" IS 'Menu 순서';
COMMENT ON COLUMN MENU_SUB_GROUP_I18N.UPDATE_TIME IS 'Menu 업데이트 시간';

CREATE TABLE MAP_SUB_GROUP_I18N
(
    ID TEXT NOT NULL PRIMARY KEY,
    NAME JSONB,
    THREE_IMAGE TEXT,
    DEPTH INTEGER,
    "order" INTEGER,
    LINK TEXT,
    PARENT_VALUE TEXT,
    MOT_IMAGE TEXT,
    JPG_IMAGE TEXT,
    THREE_ITEM_PATH JSONB,
    JPG_ITEM_PATH JSONB,
    MAP_JSON JSONB,
    UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN MAP_SUB_GROUP_I18N.ID IS '3D 지도 ID';
COMMENT ON COLUMN MAP_SUB_GROUP_I18N.NAME IS '3D 지도 이름';
COMMENT ON COLUMN MAP_SUB_GROUP_I18N.THREE_IMAGE IS '3D 지도 nas 저장 경로';
COMMENT ON COLUMN MAP_SUB_GROUP_I18N.THREE_ITEM_PATH IS '3D 지도 아이템 좌표 경로 (ThreeJS xyz)';
COMMENT ON COLUMN MAP_SUB_GROUP_I18N.JPG_IMAGE IS '2D 지도 nas 저장 경로';
COMMENT ON COLUMN MAP_SUB_GROUP_I18N.JPG_ITEM_PATH IS '2D 지도 아이템 좌표 경로';
COMMENT ON COLUMN MAP_SUB_GROUP_I18N.DEPTH IS '지도 계층';
COMMENT ON COLUMN MAP_SUB_GROUP_I18N."order" IS '3D 지도 order';
COMMENT ON COLUMN MAP_SUB_GROUP_I18N.LINK IS '3D 지도 페이지 주소';
COMMENT ON COLUMN MAP_SUB_GROUP_I18N.PARENT_VALUE IS '3D 지도 상위 값';
COMMENT ON COLUMN MAP_SUB_GROUP_I18N.MOT_IMAGE IS 'Map of tarkov 이미지';
COMMENT ON COLUMN MAP_SUB_GROUP_I18N.MAP_JSON IS '3D 지도 jsx 값';
COMMENT ON COLUMN MAP_SUB_GROUP_I18N.UPDATE_TIME IS '3D 지도 업데이트 시간';

CREATE TABLE MAP_GROUP_I18N
(
  ID TEXT NOT NULL PRIMARY KEY,
  NAME JSONB,
  THREE_IMAGE TEXT,
  THREE_ITEM_PATH JSONB,
  JPG_IMAGE TEXT,
  JPG_ITEM_PATH JSONB,
  DEPTH INTEGER,
  "order" INTEGER,
  LINK TEXT,
  MOT_IMAGE TEXT,
  MAP_JSON JSONB,
  UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN MAP_GROUP_I18N.ID IS '3D 지도 ID';
COMMENT ON COLUMN MAP_GROUP_I18N.NAME IS '3D 지도 이름';
COMMENT ON COLUMN MAP_GROUP_I18N.THREE_IMAGE IS '3D 지도 nas 저장 경로';
COMMENT ON COLUMN MAP_GROUP_I18N.THREE_ITEM_PATH IS '3D 지도 아이템 좌표 경로 (ThreeJS xyz)';
COMMENT ON COLUMN MAP_GROUP_I18N.JPG_IMAGE IS '2D 지도 nas 저장 경로';
COMMENT ON COLUMN MAP_GROUP_I18N.JPG_ITEM_PATH IS '2D 지도 아이템 좌표 경로';
COMMENT ON COLUMN MAP_GROUP_I18N.DEPTH IS '3D 지도 단계';
COMMENT ON COLUMN MAP_GROUP_I18N.LINK IS '3D 지도 페이지 주소';
COMMENT ON COLUMN MAP_GROUP_I18N."order" IS '3D 지도 order';
COMMENT ON COLUMN MAP_GROUP_I18N.MOT_IMAGE IS 'Map of tarkov 이미지';
COMMENT ON COLUMN MAP_GROUP_I18N.MAP_JSON IS '3D 지도 jsx 값';
COMMENT ON COLUMN MAP_GROUP_I18N.UPDATE_TIME IS '업데이트 시간';

CREATE TABLE QUEST_I18N
(
    id TEXT NOT NULL PRIMARY KEY,
    url_mapping TEXT,
    name JSONB,
    npc_id TEXT,
    lightkeeper_required BOOLEAN,
    kappa_required BOOLEAN,
    task_requirements JSONB,
    task_next JSONB,
    objectives JSONB,
    WIKI_URL TEXT,
    finish_rewards JSONB,
    requirements JSONB,
    guide JSONB,
    update_time timestamp with time zone DEFAULT now()
);
COMMENT ON COLUMN QUEST_I18N.id IS 'Quest ID';
COMMENT ON COLUMN QUEST_I18N.name IS 'Quest 이름';
COMMENT ON COLUMN QUEST_I18N.npc_id IS 'Quest npc id';
COMMENT ON COLUMN QUEST_I18N.lightkeeper_required IS 'Quest 라이트키퍼 여부';
COMMENT ON COLUMN QUEST_I18N.kappa_required IS 'Quest 카파 여부';
COMMENT ON COLUMN QUEST_I18N.task_requirements IS 'Quest 선행 퀘스트 목록';
COMMENT ON COLUMN QUEST_I18N.task_next IS 'Quest 후행 퀘스트 목록';
COMMENT ON COLUMN QUEST_I18N.objectives IS 'Quest 목표 목록';
COMMENT ON COLUMN QUEST_I18N.WIKI_URL IS 'Quest 위키 주소';
COMMENT ON COLUMN QUEST_I18N.GUIDE IS 'Quest 가이드';
COMMENT ON COLUMN QUEST_I18N.finish_rewards IS 'Quest 완료 보상 목록';
COMMENT ON COLUMN QUEST_I18N.requirements IS 'Quest 조건';
COMMENT ON COLUMN QUEST_I18N.url_mapping IS 'Quest url mapping';
COMMENT ON COLUMN QUEST_I18N.update_time IS 'Quest 업데이트 시간';

CREATE TABLE NPC_I18N
(
  ID TEXT NOT NULL PRIMARY KEY,
  NAME JSONB,
  IMAGE TEXT,
  "order" INTEGER,
  BARTER_INFO JSONB,
  UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN NPC_I18N.ID IS 'NPC 값';
COMMENT ON COLUMN NPC_I18N.NAME IS 'NPC 이름';
COMMENT ON COLUMN NPC_I18N.IMAGE IS 'NPC 이미지 경로';
COMMENT ON COLUMN NPC_I18N."order" IS 'NPC 순서';
COMMENT ON COLUMN NPC_I18N.BARTER_INFO IS 'NPC 연관 아이템 정보';
COMMENT ON COLUMN NPC_I18N.UPDATE_TIME IS 'NPC 업데이트 시간';

CREATE TABLE SEARCH_I18N
(
  VALUE TEXT NOT NULL,
  PAGE_VALUE TEXT NOT NULL,
  LANG TEXT NOT NULL,
  LINK TEXT,
  TYPE TEXT,
  "order" INTEGER,
  UPDATE_TIME timestamp with time zone default now(),
  primary key (VALUE, PAGE_VALUE, LANG)
);
COMMENT ON COLUMN SEARCH_I18N.VALUE IS '검색 드롭다운 값';
COMMENT ON COLUMN SEARCH_I18N.LINK IS '검색 연동 링크';
COMMENT ON COLUMN SEARCH_I18N."order" IS '검색 순서';
COMMENT ON COLUMN SEARCH_I18N.TYPE IS '검색 타입';
COMMENT ON COLUMN SEARCH_I18N.PAGE_VALUE IS '검색 페이지 값';
COMMENT ON COLUMN SEARCH_I18N.LANG IS '언어';
COMMENT ON COLUMN SEARCH_I18N.UPDATE_TIME IS '검색 업데이트 시간';

CREATE TABLE DYNAMIC_INFO_I18N
(
  ID TEXT NOT NULL PRIMARY KEY,
  JSON_VALUE JSONB,
  UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN DYNAMIC_INFO_I18N.ID IS 'DYNAMIC_INFO 아이디';
COMMENT ON COLUMN DYNAMIC_INFO_I18N.JSON_VALUE IS 'DYNAMIC_INFO json 데이터';
COMMENT ON COLUMN DYNAMIC_INFO_I18N.UPDATE_TIME IS 'DYNAMIC_INFO 업데이트 시간';

CREATE TABLE HIDEOUT_MASTER_I18N
(
    ID TEXT NOT NULL PRIMARY KEY,
    NAME JSONB,
    LEVEL_IDS TEXT[],
    UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN HIDEOUT_MASTER_I18N.ID IS 'Hideout 아이디';
COMMENT ON COLUMN HIDEOUT_MASTER_I18N.NAME IS 'Hideout 이름';
COMMENT ON COLUMN HIDEOUT_MASTER_I18N.LEVEL_IDS IS 'Hideout level 아이디 리스트';
COMMENT ON COLUMN HIDEOUT_MASTER_I18N.UPDATE_TIME IS 'Hideout 업데이트 시간';

CREATE TABLE HIDEOUT_ITEM_REQUIRE_I18N
(
    ID TEXT NOT NULL PRIMARY KEY,
    LEVEL_ID TEXT,
    ITEM_ID TEXT,
    NAME JSONB,
    QUANTITY INTEGER,
    COUNT INTEGER,
    IMAGE TEXT,
    UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN HIDEOUT_ITEM_REQUIRE_I18N.ID IS 'Hideout item require 아이디';
COMMENT ON COLUMN HIDEOUT_ITEM_REQUIRE_I18N.LEVEL_ID IS 'Hideout item require 레벨 아이디';
COMMENT ON COLUMN HIDEOUT_ITEM_REQUIRE_I18N.NAME IS 'Hideout item require 이름';
COMMENT ON COLUMN HIDEOUT_ITEM_REQUIRE_I18N.QUANTITY IS 'Hideout item require 양';
COMMENT ON COLUMN HIDEOUT_ITEM_REQUIRE_I18N.COUNT IS 'Hideout item require 개수';
COMMENT ON COLUMN HIDEOUT_ITEM_REQUIRE_I18N.IMAGE IS 'Hideout item require 이미지';
COMMENT ON COLUMN HIDEOUT_ITEM_REQUIRE_I18N.ITEM_ID IS 'Hideout item require 아이템 아이디';
COMMENT ON COLUMN HIDEOUT_ITEM_REQUIRE_I18N.UPDATE_TIME IS 'Hideout item require 업데이트 시간';

CREATE TABLE HIDEOUT_LEVEL_I18N
(
    ID TEXT NOT NULL PRIMARY KEY,
    LEVEL INTEGER,
    CONSTRUCTION_TIME INTEGER,
    UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN HIDEOUT_LEVEL_I18N.ID IS 'Hideout level 아이디';
COMMENT ON COLUMN HIDEOUT_LEVEL_I18N.ID IS 'Hideout level 값';
COMMENT ON COLUMN HIDEOUT_LEVEL_I18N.ID IS 'Hideout level 건축 시간';
COMMENT ON COLUMN HIDEOUT_LEVEL_I18N.UPDATE_TIME IS 'Hideout level 업데이트 시간';

CREATE TABLE HIDEOUT_TRADER_REQUIRE_I18N
(
    ID TEXT NOT NULL PRIMARY KEY,
    LEVEL_ID TEXT,
    NAME JSONB,
    VALUE INTEGER,
    IMAGE TEXT,
    UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN HIDEOUT_TRADER_REQUIRE_I18N.ID IS 'Hideout trader 아이디';
COMMENT ON COLUMN HIDEOUT_TRADER_REQUIRE_I18N.LEVEL_ID IS 'Hideout trader 레벨 아이디';
COMMENT ON COLUMN HIDEOUT_TRADER_REQUIRE_I18N.NAME IS 'Hideout trader 이름';
COMMENT ON COLUMN HIDEOUT_TRADER_REQUIRE_I18N.VALUE IS 'Hideout trader 값';
COMMENT ON COLUMN HIDEOUT_TRADER_REQUIRE_I18N.IMAGE IS 'Hideout trader 이미지';
COMMENT ON COLUMN HIDEOUT_TRADER_REQUIRE_I18N.UPDATE_TIME IS 'Hideout trader 업데이트 시간';

CREATE TABLE HIDEOUT_STATION_REQUIRE_I18N
(
    ID TEXT NOT NULL PRIMARY KEY,
    STATION_MASTER_ID TEXT,
    LEVEL_ID TEXT,
    LEVEL INTEGER,
    NAME JSONB,
    UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN HIDEOUT_STATION_REQUIRE_I18N.ID IS 'Hideout station require 아이디';
COMMENT ON COLUMN HIDEOUT_STATION_REQUIRE_I18N.LEVEL_ID IS 'Hideout station require 레벨 아이디';
COMMENT ON COLUMN HIDEOUT_STATION_REQUIRE_I18N.LEVEL IS 'Hideout station require 레벨';
COMMENT ON COLUMN HIDEOUT_STATION_REQUIRE_I18N.NAME IS 'Hideout station require 이름';
COMMENT ON COLUMN HIDEOUT_STATION_REQUIRE_I18N.station_master_id IS 'Hideout station master 아이디';
COMMENT ON COLUMN HIDEOUT_STATION_REQUIRE_I18N.UPDATE_TIME IS 'Hideout station require 업데이트 시간';

CREATE TABLE HIDEOUT_CRAFTS_I18N
(
    ID TEXT NOT NULL PRIMARY KEY,
    LEVEL_ID TEXT,
    LEVEL INTEGER,
    NAME JSONB,
    REWARD_ITEM_ID TEXT,
    WIDTH NUMERIC,
    HEIGHT NUMERIC,
    DURATION NUMERIC,
    IMAGE TEXT,
    QUANTITY NUMERIC,
    REQ_ITEM JSONB,
    UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN HIDEOUT_CRAFTS_I18N.ID IS 'Hideout crafts 아이디';
COMMENT ON COLUMN HIDEOUT_CRAFTS_I18N.LEVEL_ID IS 'Hideout crafts 레벨 아이디';
COMMENT ON COLUMN HIDEOUT_CRAFTS_I18N.LEVEL IS 'Hideout crafts 레벨';
COMMENT ON COLUMN HIDEOUT_CRAFTS_I18N.WIDTH IS 'Hideout crafts 아이템 가로 길이';
COMMENT ON COLUMN HIDEOUT_CRAFTS_I18N.HEIGHT IS 'Hideout crafts 아이템 세로 길이';
COMMENT ON COLUMN HIDEOUT_CRAFTS_I18N.NAME IS 'Hideout crafts 이름';
COMMENT ON COLUMN HIDEOUT_CRAFTS_I18N.DURATION IS 'Hideout crafts 시간';
COMMENT ON COLUMN HIDEOUT_CRAFTS_I18N.REQ_ITEM IS 'Hideout crafts 필요 아이템 리스트';
COMMENT ON COLUMN HIDEOUT_CRAFTS_I18N.IMAGE IS 'Hideout crafts 아이템 사진';
COMMENT ON COLUMN HIDEOUT_CRAFTS_I18N.QUANTITY IS 'Hideout crafts 아이템 보상 개수';
COMMENT ON COLUMN HIDEOUT_CRAFTS_I18N.REWARD_ITEM_ID IS 'Hideout crafts 보상 아이템 아이디';
COMMENT ON COLUMN HIDEOUT_CRAFTS_I18N.UPDATE_TIME IS 'Hideout crafts 업데이트 시간';

CREATE TABLE HIDEOUT_SKILL_REQUIRE_I18N
(
    ID TEXT NOT NULL PRIMARY KEY,
    LEVEL_ID TEXT,
    LEVEL INTEGER,
    NAME JSONB,
    IMAGE TEXT,
    UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN HIDEOUT_SKILL_REQUIRE_I18N.ID IS 'Hideout skill require 아이디';
COMMENT ON COLUMN HIDEOUT_SKILL_REQUIRE_I18N.LEVEL_ID IS 'Hideout skill require 레벨 아이디';
COMMENT ON COLUMN HIDEOUT_SKILL_REQUIRE_I18N.LEVEL IS 'Hideout skill require 레벨';
COMMENT ON COLUMN HIDEOUT_SKILL_REQUIRE_I18N.NAME IS 'Hideout skill require 이름';
COMMENT ON COLUMN HIDEOUT_SKILL_REQUIRE_I18N.IMAGE IS 'Hideout skill require 사진';
COMMENT ON COLUMN HIDEOUT_SKILL_REQUIRE_I18N.UPDATE_TIME IS 'Hideout skill require 업데이트 시간';

CREATE TABLE HIDEOUT_BONUS_I18N
(
    LEVEL_ID TEXT NOT NULL,
    TYPE TEXT NOT NULL,
    NAME JSONB,
    SKILL_NAME JSONB,
    VALUE NUMERIC(10, 4),
    UPDATE_TIME timestamp with time zone default now(),
    PRIMARY KEY (LEVEL_ID, TYPE)
);
COMMENT ON COLUMN HIDEOUT_BONUS_I18N.LEVEL_ID IS 'Hideout bonus 레벨 아이디';
COMMENT ON COLUMN HIDEOUT_BONUS_I18N.TYPE IS 'Hideout bonus 타입';
COMMENT ON COLUMN HIDEOUT_BONUS_I18N.NAME IS 'Hideout bonus 이름';
COMMENT ON COLUMN HIDEOUT_BONUS_I18N.VALUE IS 'Hideout bonus 값';
COMMENT ON COLUMN HIDEOUT_BONUS_I18N.SKILL_NAME IS 'Hideout bonus 스킬 이름';
COMMENT ON COLUMN HIDEOUT_BONUS_I18N.UPDATE_TIME IS 'Hideout bonus 아이디';

CREATE TABLE USER_INFO
(
  ID TEXT primary key,
  NAME TEXT,
  EMAIL TEXT,
  IS_ADMIN BOOLEAN,
  ATTENDANCE_COUNT INTEGER,
  CREATE_TIME timestamp with time zone default now(),
  ATTENDANCE_TIME timestamp with time zone
);
COMMENT ON COLUMN USER_INFO.ID IS '사용자 아이디';
COMMENT ON COLUMN USER_INFO.NAME IS '사용자 이름';
COMMENT ON COLUMN USER_INFO.EMAIL IS '사용자 이메일';
COMMENT ON COLUMN USER_INFO.IS_ADMIN IS '사용자 운영자 여부';
COMMENT ON COLUMN USER_INFO.ATTENDANCE_COUNT IS '사용자 출석일 수';
COMMENT ON COLUMN USER_INFO.CREATE_TIME IS '사용자 생성일';
COMMENT ON COLUMN USER_INFO.ATTENDANCE_TIME IS '사용자 최근 출석 날짜';

CREATE TABLE USER_QUEST
(
  USER_EMAIL TEXT,
  QUEST_LIST TEXT[],
  UPDATE_TIME timestamp with time zone default now(),
  PRIMARY KEY (USER_EMAIL)
);
COMMENT ON COLUMN USER_QUEST.USER_EMAIL IS '사용자 이메일';
COMMENT ON COLUMN USER_QUEST.QUEST_LIST IS '사용자 퀘스트 리스트';
COMMENT ON COLUMN USER_QUEST.UPDATE_TIME IS '사용자 퀘스트 업데이트 시간';

CREATE TABLE PATCH_NOTES_I18N
(
    ID TEXT NOT NULL PRIMARY KEY,
    NAME JSONB,
    DESCRIPTION JSONB,
    UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN PATCH_NOTES_I18N.ID IS '패치 노트 ID';
COMMENT ON COLUMN PATCH_NOTES_I18N.NAME IS '패치 노트 이름';
COMMENT ON COLUMN PATCH_NOTES_I18N.DESCRIPTION IS '패치 노트 내용';
COMMENT ON COLUMN PATCH_NOTES_I18N.UPDATE_TIME IS '패치 노트 업데이트 시간';

CREATE TABLE NOTICE_I18N
(
    ID TEXT NOT NULL PRIMARY KEY,
    NAME JSONB,
    DESCRIPTION JSONB,
    UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN NOTICE_I18N.ID IS '공지사항 ID';
COMMENT ON COLUMN NOTICE_I18N.NAME IS '공지사항 이름';
COMMENT ON COLUMN NOTICE_I18N.DESCRIPTION IS '공지사항 내용';
COMMENT ON COLUMN NOTICE_I18N.UPDATE_TIME IS '공지사항 업데이트 시간';

CREATE TABLE EVENT_I18N
(
    ID TEXT NOT NULL PRIMARY KEY,
    NAME JSONB,
    DESCRIPTION JSONB,
    UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN EVENT_I18N.ID IS 'Event ID';
COMMENT ON COLUMN EVENT_I18N.NAME IS 'Event 이름';
COMMENT ON COLUMN EVENT_I18N.DESCRIPTION IS 'Event 내용';
COMMENT ON COLUMN EVENT_I18N.UPDATE_TIME IS 'Event 업데이트 시간';

CREATE TABLE USER_ROADMAP
(
    USER_EMAIL TEXT primary key,
    QUEST_LIST TEXT[],
    UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN USER_ROADMAP.USER_EMAIL IS '로드맵 사용자 이메일';
COMMENT ON COLUMN USER_ROADMAP.QUEST_LIST IS '로드맵 완료한 퀘스트 정보';
COMMENT ON COLUMN USER_ROADMAP.UPDATE_TIME IS '로드맵 업데이트 날짜';

CREATE TABLE ROADMAP_NODE
(
    ID TEXT primary key,
    TOTAL_X_COORDINATE NUMERIC,
    TOTAL_Y_COORDINATE NUMERIC,
    SINGLE_X_COORDINATE NUMERIC,
    SINGLE_Y_COORDINATE NUMERIC,
    NODE_COLOR TEXT,
    UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN ROADMAP_NODE.ID IS '로드맵 퀘스트 아이디';
COMMENT ON COLUMN ROADMAP_NODE.TOTAL_X_COORDINATE IS '로드맵 전체 X 좌표';
COMMENT ON COLUMN ROADMAP_NODE.TOTAL_Y_COORDINATE IS '로드맵 전체 Y 좌표';
COMMENT ON COLUMN ROADMAP_NODE.SINGLE_X_COORDINATE IS '로드맵 싱글 X 좌표';
COMMENT ON COLUMN ROADMAP_NODE.SINGLE_Y_COORDINATE IS '로드맵 싱글 Y 좌표';
COMMENT ON COLUMN ROADMAP_NODE.NODE_COLOR IS '로드맵 노드 색상';
COMMENT ON COLUMN ROADMAP_NODE.UPDATE_TIME IS '로드맵 업데이트 날짜';

CREATE TABLE ROADMAP_EDGE
(
    ID TEXT primary key,
    SOURCE_ID TEXT,
    TARGET_ID TEXT,
    UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN ROADMAP_EDGE.ID IS '로드맵 엣지 아이디';
COMMENT ON COLUMN ROADMAP_EDGE.SOURCE_ID IS '로드맵 엣지 연결 시작 노드 아이디';
COMMENT ON COLUMN ROADMAP_EDGE.TARGET_ID IS '로드맵 엣지 연결 끝 노드 아이디';
COMMENT ON COLUMN ROADMAP_EDGE.UPDATE_TIME IS '로드맵 엣지 업데이트 날짜';

CREATE TABLE ITEM_PRICE_I18N
(
    ID TEXT primary key ,
    NAME JSONB,
    WIDTH numeric,
    HEIGHT numeric,
    CATEGORY TEXT,
    TRADER JSONB,
    IMAGE TEXT,
    UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN ITEM_PRICE_I18N.ID IS '아이템 아이디';
COMMENT ON COLUMN ITEM_PRICE_I18N.NAME IS '아이템 이름';
COMMENT ON COLUMN ITEM_PRICE_I18N.IMAGE IS '아이템 사진';
COMMENT ON COLUMN ITEM_PRICE_I18N.WIDTH IS '아이템 가로 크기';
COMMENT ON COLUMN ITEM_PRICE_I18N.HEIGHT IS '아이템 세로 크기';
COMMENT ON COLUMN ITEM_PRICE_I18N.CATEGORY IS '아이템 카테고리';
COMMENT ON COLUMN ITEM_PRICE_I18N.TRADER IS '트레이더 정보';
COMMENT ON COLUMN ITEM_PRICE_I18N.UPDATE_TIME IS '업데이트 날짜';

CREATE TABLE ITEM_PRICE_HISTORY_I18N
(
    ID TEXT,
    PRICE INTEGER,
    PRICE_TYPE TEXT,
    PRICE_TIME timestamp with time zone default now(),
    EXECUTE_TIME timestamp with time zone default now(),
    PRIMARY KEY (ID, PRICE_TYPE, PRICE_TIME)
);
COMMENT ON COLUMN ITEM_PRICE_HISTORY_I18N.ID IS '아이템 아이디';
COMMENT ON COLUMN ITEM_PRICE_HISTORY_I18N.PRICE IS '해당 시간대 금액';
COMMENT ON COLUMN ITEM_PRICE_HISTORY_I18N.PRICE_TYPE IS '시세 종류 (pvp, pve)';
COMMENT ON COLUMN ITEM_PRICE_HISTORY_I18N.PRICE_TIME IS '아이템 시세 시간대';
COMMENT ON COLUMN ITEM_PRICE_HISTORY_I18N.EXECUTE_TIME IS '적재 날짜';

CREATE TABLE WIPE_I18N
(
    ID INTEGER primary key ,
    PATCH_VERSION TEXT,
    SEASON_START TEXT,
    SEASON_END TEXT,
    CREATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN WIPE_I18N.ID IS '아이디';
COMMENT ON COLUMN WIPE_I18N.PATCH_VERSION IS '패치 버전';
COMMENT ON COLUMN WIPE_I18N.SEASON_START IS '시즌 시작 날짜';
COMMENT ON COLUMN WIPE_I18N.SEASON_END IS '시즌 종료 날짜';
COMMENT ON COLUMN WIPE_I18N.CREATE_TIME IS '생성 날짜';

CREATE TABLE USER_HIDEOUT
(
    USER_EMAIL TEXT primary key,
    COMPLETE_LIST TEXT[],
    UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN USER_HIDEOUT.USER_EMAIL IS '하이드아웃 사용자 이메일';
COMMENT ON COLUMN USER_HIDEOUT.COMPLETE_LIST IS '하이드아웃 완료 정보';
COMMENT ON COLUMN USER_HIDEOUT.UPDATE_TIME IS '하이드아웃 업데이트 날짜';

CREATE TABLE ITEM_I18N
(
    ID TEXT NOT NULL PRIMARY KEY,
    NAME JSONB,
    CATEGORY TEXT,
    IMAGE_WIDTH NUMERIC,
    IMAGE_HEIGHT NUMERIC,
    URL_MAPPING TEXT,
    IMAGE TEXT,
    INFO JSONB,
    UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN ITEM_I18N.ID IS '아이템 아이디';
COMMENT ON COLUMN ITEM_I18N.NAME IS '아이템 이름';
COMMENT ON COLUMN ITEM_I18N.CATEGORY IS '아이템 카테고리';
COMMENT ON COLUMN ITEM_I18N.IMAGE IS '아이템 사진';
COMMENT ON COLUMN ITEM_I18N.IMAGE_WIDTH IS '아이템 사진 가로 크기';
COMMENT ON COLUMN ITEM_I18N.IMAGE_HEIGHT IS '아이템 사진 세로 크기';
COMMENT ON COLUMN ITEM_I18N.URL_MAPPING IS '아이템 주소';
COMMENT ON COLUMN ITEM_I18N.INFO IS '아이템 상세 정보';
COMMENT ON COLUMN ITEM_I18N.UPDATE_TIME IS '아이템 업데이트 날짜';

CREATE TABLE WHERE_AM_I_I18N
(
    ID TEXT NOT NULL PRIMARY KEY,
    IMAGE TEXT,
    MAP_BOUNDS JSONB,
    IMAGE_BOUNDS JSONB,
    UPDATE_TIME timestamp with time zone default now()
);
COMMENT ON COLUMN WHERE_AM_I_I18N.ID IS 'where am i 아이디';
COMMENT ON COLUMN WHERE_AM_I_I18N.IMAGE IS 'where am i 이미지';
COMMENT ON COLUMN WHERE_AM_I_I18N.MAP_BOUNDS IS 'where am i Map bounds';
COMMENT ON COLUMN WHERE_AM_I_I18N.IMAGE_BOUNDS IS 'where am i image bounds';
COMMENT ON COLUMN WHERE_AM_I_I18N.UPDATE_TIME IS 'where am i 업데이트 날짜';