from enum import Enum


class Message(Enum):
    SUCCESS = "OK"
    MAP_NOT_FOUND = "Map not found"
    NEWS_NOT_FOUND = "News not found"
    WIPE_NOT_FOUND = "Wipe not found"
    CHART_NOT_FOUND = "Chart not found"
    MENU_NOT_FOUND = "Menu not found"
    NPC_NOT_FOUND = "NPC not found"
    QUEST_NOT_FOUND = "Quest not found"
    EVENT_NOT_FOUND = "Event not found"
    PRICE_NOT_FOUND = "Price not found"
    PATCH_NOTES_NOT_FOUND = "Patch notes not found"
    NOTICE_NOT_FOUND = "Notice not found"
    ITEM_NOT_FOUND = "Item not found"
    MAIN_INFO_NOT_FOUND = "Main info not found"
    BOSS_NOT_FOUND = "Boss not found"
    MAP_OF_TARKOV_NOT_FOUND = "Map of tarkov not found"
    COLUMN_NOT_FOUND = "Column not found"
    SEARCH_NOT_FOUND = "SEARCH not found"
    SITE_LIST_NOT_FOUND = "Site list not found"
    ITEM_FILTER_NOT_FOUND = "Item filter not found"
    ITEM_LIST_NOT_FOUNT = "Item list not found"
    HIDEOUT_NOT_FOUND = "Hideout not found"
    USER_ADD_FAIL = "User add fail"
    USER_DELETE_FAIL = "User delete fail"
    INVALID_USER = "Invalid User"
    SUCCESS_QUEST_FAIL = "Success quest fail"
    GET_ROADMAP_FAIL = "Get Roadmap fail"
    ROADMAP_SAVE_FAIL = "Roadmap save fail"
    COMMUNITY_FAIL = "Community fail"
    STATION_SAVE_FAIL = "Station save fail"
    IMAGE_UPLOAD_FAIL = "Image upload fail"
